import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@/services/trpc/provider";
import URQLProvider from "@/components/providers/urql";
import { ToastProvider } from "@/components/ui/toast";
import JotaiProvider from "@/components/providers/jotai";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins antialiased`}>
        <ToastProvider>
          <JotaiProvider>
            <TRPCProvider>
              <URQLProvider>{children}</URQLProvider>
            </TRPCProvider>
          </JotaiProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
